# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'autoriz.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_autoriz(object):
    def setupUi(self, autoriz):
        autoriz.setObjectName("autoriz")
        autoriz.resize(372, 280)
        self.enter = QtWidgets.QPushButton(autoriz)
        self.enter.setGeometry(QtCore.QRect(80, 210, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.enter.setFont(font)
        self.enter.setObjectName("enter")
        self.label = QtWidgets.QLabel(autoriz)
        self.label.setGeometry(QtCore.QRect(40, 40, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pass_le = QtWidgets.QLineEdit(autoriz)
        self.pass_le.setGeometry(QtCore.QRect(120, 120, 181, 41))
        self.pass_le.setObjectName("pass_le")
        self.login_le = QtWidgets.QLineEdit(autoriz)
        self.login_le.setGeometry(QtCore.QRect(120, 30, 181, 41))
        self.login_le.setObjectName("login_le")
        self.label_3 = QtWidgets.QLabel(autoriz)
        self.label_3.setGeometry(QtCore.QRect(50, 120, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(autoriz)
        QtCore.QMetaObject.connectSlotsByName(autoriz)

    def retranslateUi(self, autoriz):
        _translate = QtCore.QCoreApplication.translate
        autoriz.setWindowTitle(_translate("autoriz", "autoriz"))
        self.enter.setText(_translate("autoriz", "Enter"))
        self.label.setText(_translate("autoriz", "Login"))
        self.label_3.setText(_translate("autoriz", "Pass"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    autoriz = QtWidgets.QWidget()
    ui = Ui_autoriz()
    ui.setupUi(autoriz)
    autoriz.show()
    sys.exit(app.exec_())
