# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lkabinet.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_lkabinet(object):
    def setupUi(self, lkabinet):
        lkabinet.setObjectName("lkabinet")
        lkabinet.resize(478, 532)
        self.lineEdit = QtWidgets.QLineEdit(lkabinet)
        self.lineEdit.setGeometry(QtCore.QRect(180, 20, 191, 51))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(lkabinet)
        self.lineEdit_2.setGeometry(QtCore.QRect(180, 100, 191, 51))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(lkabinet)
        self.lineEdit_3.setGeometry(QtCore.QRect(180, 180, 191, 51))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(lkabinet)
        self.lineEdit_4.setGeometry(QtCore.QRect(180, 260, 191, 51))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(lkabinet)
        self.lineEdit_5.setGeometry(QtCore.QRect(180, 340, 191, 51))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.save = QtWidgets.QPushButton(lkabinet)
        self.save.setGeometry(QtCore.QRect(120, 420, 251, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.save.setFont(font)
        self.save.setObjectName("save")
        self.label = QtWidgets.QLabel(lkabinet)
        self.label.setGeometry(QtCore.QRect(100, 30, 55, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(lkabinet)
        self.label_2.setGeometry(QtCore.QRect(100, 120, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(lkabinet)
        self.label_3.setGeometry(QtCore.QRect(110, 360, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(lkabinet)
        self.label_4.setGeometry(QtCore.QRect(100, 260, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(lkabinet)
        self.label_5.setGeometry(QtCore.QRect(100, 200, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")

        self.retranslateUi(lkabinet)
        QtCore.QMetaObject.connectSlotsByName(lkabinet)

    def retranslateUi(self, lkabinet):
        _translate = QtCore.QCoreApplication.translate
        lkabinet.setWindowTitle(_translate("lkabinet", "lkabinet"))
        self.save.setText(_translate("lkabinet", "Save"))
        self.label.setText(_translate("lkabinet", "login"))
        self.label_2.setText(_translate("lkabinet", "pass"))
        self.label_3.setText(_translate("lkabinet", "dr"))
        self.label_4.setText(_translate("lkabinet", "gruppa"))
        self.label_5.setText(_translate("lkabinet", "name"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    lkabinet = QtWidgets.QWidget()
    ui = Ui_lkabinet()
    ui.setupUi(lkabinet)
    lkabinet.show()
    sys.exit(app.exec_())
